version: '3'

services:
  web:
    build: .
    ports:
      - "8300:8300"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./prompts.db
    command: uvicorn backend:app --host 0.0.0.0 --port 8300 --reload --log-level debug
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"